const $ = (s)=>document.querySelector(s);
const store = {
  get(k,d){ try{return JSON.parse(localStorage.getItem(k)) ?? d}catch{return d}},
  set(k,v){localStorage.setItem(k,JSON.stringify(v))}
};
const todayKey=()=>new Date().toISOString().slice(0,10);
const fmtDate=(d=new Date())=>`${d.getMonth()+1}月${d.getDate()}日`;
const defaults={kcal:2000,p:120,f:60,c:250};
let state={tab:'today',date:todayKey(),target:store.get('target',defaults),meals:store.get('meals',{}),weights:store.get('weights',[]),camera:null};
const foodDB=[
{name:'白ご飯 150g',kcal:234,p:3.8,f:.5,c:55.7},{name:'白ご飯 180g',kcal:281,p:4.5,f:.6,c:66.8},{name:'納豆 1パック',kcal:90,p:7.4,f:4.5,c:5.4},{name:'卵 1個',kcal:76,p:6.2,f:5.2,c:.2},{name:'味噌汁 1杯',kcal:45,p:2.5,f:1.5,c:5},{name:'サラダチキン 1個',kcal:115,p:23,f:1.5,c:1.5},{name:'鮭おにぎり 1個',kcal:190,p:4.5,f:2,c:38},{name:'唐揚げ 1個',kcal:82,p:5.1,f:5.2,c:3.4},{name:'プロテイン 1杯',kcal:120,p:24,f:2,c:4},{name:'バナナ 1本',kcal:93,p:1.1,f:.2,c:22.5}];
function dayMeals(){return state.meals[state.date]||[]}
function totals(){return dayMeals().reduce((a,x)=>({kcal:a.kcal+x.kcal,p:a.p+x.p,f:a.f+x.f,c:a.c+x.c}),{kcal:0,p:0,f:0,c:0})}
function pct(v,t){return Math.min(100,Math.round(v/t*100))}
function saveMeals(){store.set('meals',state.meals)}
function nav(){return `<nav class="bottom">${[['today','🏠','今日'],['analysis','📊','分析'],['weight','⚖️','体重'],['ai','🤖','AI相談'],['settings','⚙️','設定']].map(x=>`<button class="nav ${state.tab===x[0]?'active':''}" data-tab="${x[0]}"><span class="ico">${x[1]}</span>${x[2]}</button>`).join('')}</nav>`}
function header(title,back=false){return `<header class="top">${back?'<button class="topbtn" id="back">‹</button>':'<span></span>'}<div style="text-align:center"><div class="title">${title}</div>${title==='今日'?`<div class="date">${fmtDate(new Date(state.date+'T12:00:00'))}</div>`:''}</div><span></span></header>`}
function today(){const t=totals(),r=Math.max(0,state.target.kcal-t.kcal);const groups=['朝食','昼食','夕食','間食'];return `${header('今日')}<section class="card hero"><div class="remaining">あと <b>${Math.round(r)}</b> kcal</div><div class="sub">${Math.round(t.kcal).toLocaleString()} / ${state.target.kcal.toLocaleString()} kcal</div><div class="bar"><span style="width:${pct(t.kcal,state.target.kcal)}%"></span></div><div class="macros">${macro('たんぱく質',t.p,state.target.p,'var(--green)')}${macro('脂質',t.f,state.target.f,'var(--orange)')}${macro('炭水化物',t.c,state.target.c,'var(--yellow)')}</div></section><section class="card" style="padding:0">${groups.map(g=>mealGroup(g)).join('')}</section><div style="padding:0 16px"><button class="primary" id="addMeal">＋ 食事を記録</button></div><div class="notice"><b>🤖 AIアドバイス</b><br>${advice(t)}</div>${nav()}`}
function macro(n,v,t,color){return `<div class="macro"><small>${n}</small><strong>${Math.round(v)} / ${t}g</strong><div class="mini"><span style="width:${pct(v,t)}%;background:${color}"></span></div></div>`}
function mealGroup(g){const xs=dayMeals().filter(x=>x.type===g);const k=xs.reduce((a,x)=>a+x.kcal,0);return `<div class="meal"><div><h3>${g}</h3><p>${xs.length?xs.map(x=>x.name).join('・'):'未登録'}</p></div><div class="kcal">${xs.length?Math.round(k)+' kcal':'＋'}</div></div>`}
function advice(t){const p=Math.max(0,Math.round(state.target.p-t.p)),f=Math.max(0,Math.round(state.target.f-t.f));return p>0?`たんぱく質があと${p}g不足しています。${f<15?'脂質は残り少なめなので、鶏むね肉・魚・豆腐などがおすすめです。':'夕食で主菜をしっかり取ると目標に近づきます。'}`:'たんぱく質は目標圏内です。残りカロリーを見ながら調整しましょう。'}
function addMeal(){return `${header('食事を記録',true)}<div class="section-title">記録方法を選んでください</div><section class="card grid"><button class="method camera" id="camera"><b>📷 写真からAI解析</b><span>iPhoneカメラで撮影できます（解析接続は次版）</span></button><button class="method search" id="searchFood"><b>🔎 食品・料理を検索</b><span>登録済み食品から追加</span></button><button class="method manual" id="manual"><b>✏️ 手入力</b><span>食品名・量・栄養を直接入力</span></button></section>`}
function searchFood(){return `${header('食品・料理を検索',true)}<section class="card"><div class="field"><label>検索</label><input id="q" placeholder="例：ご飯、卵、プロテイン"></div><div class="field"><label>食事区分</label><select id="mealType"><option>朝食</option><option>昼食</option><option>夕食</option><option>間食</option></select></div><div id="foods" class="food-list">${foodsHtml(foodDB)}</div></section>`}
function foodsHtml(xs){return xs.map((f,i)=>`<div class="food"><div><b>${f.name}</b><br><small>${f.kcal} kcal / P${f.p} F${f.f} C${f.c}</small></div><button class="chip addFood" data-name="${encodeURIComponent(f.name)}">追加</button></div>`).join('')}
function manual(){return `${header('手入力',true)}<section class="card"><div class="field"><label>食品名</label><input id="name" placeholder="例：焼き魚"></div><div class="field"><label>食事区分</label><select id="type"><option>朝食</option><option>昼食</option><option>夕食</option><option>間食</option></select></div><div class="field"><label>カロリー</label><input id="kcal" type="number" inputmode="decimal" value="0"></div><div class="row"><div class="field"><label>P (g)</label><input id="p" type="number" inputmode="decimal" value="0"></div><div class="field"><label>F (g)</label><input id="f" type="number" inputmode="decimal" value="0"></div></div><div class="field"><label>C (g)</label><input id="c" type="number" inputmode="decimal" value="0"></div><button class="primary" id="saveManual">登録する</button></section>`}
function camera(){return `${header('写真から記録',true)}<section class="card"><span class="badge">iPhoneカメラ対応</span><p class="muted">料理写真を撮影または選択してください。今回のテスト版では写真取得とプレビューまで確認できます。</p><input id="photo" type="file" accept="image/*" capture="environment" style="width:100%;margin:12px 0"> <div id="previewArea"></div><div class="notice" style="margin:12px 0 0">AIによる料理名・量・カロリー推定はVersion 0.2で接続します。</div></section>`}
function analysis(){const days=[...Array(7)].map((_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));const k=d.toISOString().slice(0,10);const xs=state.meals[k]||[];return {k,v:xs.reduce((a,x)=>a+x.kcal,0)}});const max=Math.max(state.target.kcal,...days.map(x=>x.v));return `${header('分析')}<section class="card"><b>直近7日間の摂取カロリー</b><div class="chart">${days.map(x=>`<div class="barcol"><i style="height:${Math.max(4,130*x.v/max)}px"></i>${x.k.slice(5)}</div>`).join('')}</div></section><section class="card"><div class="stat"><span>7日平均</span><b>${Math.round(days.reduce((a,x)=>a+x.v,0)/7)} kcal</b></div><div class="stat"><span>目標</span><b>${state.target.kcal} kcal</b></div></section>${nav()}`}
function weight(){const last=state.weights.at(-1);return `${header('体重')}<section class="card"><div class="field"><label>今日の体重 (kg)</label><input id="weightInput" type="number" inputmode="decimal" step="0.1" value="${last?.value||''}" placeholder="例：71.8"></div><button class="primary" id="saveWeight">保存する</button></section><section class="card"><b>最近の記録</b>${state.weights.length?state.weights.slice(-7).reverse().map(x=>`<div class="stat"><span>${x.date}</span><b>${x.value} kg</b></div>`).join(''):'<div class="empty">まだ記録がありません</div>'}</section>${nav()}`}
function ai(){const t=totals();return `${header('AI相談')}<section class="card"><div class="notice" style="margin:0"><b>現在の状態</b><br>残り ${Math.max(0,Math.round(state.target.kcal-t.kcal))} kcal / たんぱく質あと ${Math.max(0,Math.round(state.target.p-t.p))}g</div><p class="muted">Version 0.2では「コンビニで何を買えばいい？」「ラーメン食べてもいい？」のような相談を、当日の残り栄養量を使って回答できるようにします。</p><button class="secondary" disabled>AI相談（次版で有効化）</button></section>${nav()}`}
function settings(){const x=state.target;return `${header('設定')}<section class="card"><div class="field"><label>目標カロリー</label><input id="tk" type="number" value="${x.kcal}"></div><div class="row"><div class="field"><label>P (g)</label><input id="tp" type="number" value="${x.p}"></div><div class="field"><label>F (g)</label><input id="tf" type="number" value="${x.f}"></div></div><div class="field"><label>C (g)</label><input id="tc" type="number" value="${x.c}"></div><button class="primary" id="saveSettings">保存する</button></section><section class="card"><button class="secondary danger" id="reset">テストデータを初期化</button></section>${nav()}`}
function render(view=state.tab){const app=$('#app'); if(view==='add')app.innerHTML=`<div class="app">${addMeal()}</div>`; else if(view==='search')app.innerHTML=`<div class="app">${searchFood()}</div>`; else if(view==='manual')app.innerHTML=`<div class="app">${manual()}</div>`; else if(view==='camera')app.innerHTML=`<div class="app">${camera()}</div>`; else {state.tab=view; const f={today,analysis,weight,ai,settings}[view]||today;app.innerHTML=`<div class="app">${f()}</div>`} bind(view)}
function bind(view){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>render(b.dataset.tab)); const back=$('#back'); if(back)back.onclick=()=>render(view==='search'||view==='manual'||view==='camera'?'add':'today'); if($('#addMeal'))$('#addMeal').onclick=()=>render('add'); if($('#searchFood'))$('#searchFood').onclick=()=>render('search'); if($('#manual'))$('#manual').onclick=()=>render('manual'); if($('#camera'))$('#camera').onclick=()=>render('camera');
 if(view==='search'){const q=$('#q'),foods=$('#foods');q.oninput=()=>{const s=q.value.trim();foods.innerHTML=foodsHtml(foodDB.filter(f=>f.name.includes(s)))};document.addEventListener('click',addFoodOnce,{once:true,capture:true});}
 if(view==='manual')$('#saveManual').onclick=()=>{const item={name:$('#name').value.trim()||'手入力',type:$('#type').value,kcal:+$('#kcal').value||0,p:+$('#p').value||0,f:+$('#f').value||0,c:+$('#c').value||0};addItem(item)};
 if(view==='camera')$('#photo').onchange=(e)=>{const f=e.target.files?.[0];if(!f)return;const url=URL.createObjectURL(f);$('#previewArea').innerHTML=`<img class="preview" src="${url}"><button class="secondary" id="demoAdd">写真確認OK（デモ食事を登録）</button>`;$('#demoAdd').onclick=()=>addItem({name:'写真からのデモ登録',type:'昼食',kcal:500,p:25,f:18,c:58})};
 if(view==='weight')$('#saveWeight').onclick=()=>{const v=+$('#weightInput').value;if(!v)return alert('体重を入力してください');state.weights.push({date:todayKey(),value:v});state.weights=state.weights.slice(-90);store.set('weights',state.weights);render('weight')};
 if(view==='settings'){ $('#saveSettings').onclick=()=>{state.target={kcal:+$('#tk').value||2000,p:+$('#tp').value||120,f:+$('#tf').value||60,c:+$('#tc').value||250};store.set('target',state.target);alert('保存しました');render('settings')}; $('#reset').onclick=()=>{if(confirm('端末内のテストデータを削除しますか？')){localStorage.clear();location.reload()}}}
}
function addFoodOnce(e){const b=e.target.closest('.addFood');if(!b)return;const f=foodDB.find(x=>x.name===decodeURIComponent(b.dataset.name));if(!f)return;addItem({...f,type:$('#mealType').value})}
function addItem(item){state.meals[state.date]=[...(state.meals[state.date]||[]),item];saveMeals();render('today')}
render('today');
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
